"""Phase B.5 — coverage audit.

Walks ``$HOME``, classifies every visible item against the known migration
channels, and surfaces anything that would fall through. Two phases:

1. **Static survey** (no LLM). Walk top-level + a curated set of hidden dirs,
   hash each item against known patterns:

   - ``chezmoi-managed`` — present in chezmoi's source tree
   - ``pack-personal-default`` — in ``pack-personal.sh``'s default targets
   - ``pack-browsers-default`` — Firefox / Chromium-family / Cursor profile dirs
   - ``pack-secrets-default`` — ``~/.config/secrets``
   - ``pack-creds-conditional`` — covered by ``INCLUDE_CREDS=1``
   - ``pack-wallets-conditional`` — covered by ``INCLUDE_WALLETS=1``
   - ``regenerable`` — well-known cache / build / vendored-tooling pattern
   - ``uncovered`` — falls through every bucket; the agent should look at it

2. **Agentic deep-dive** (``--via-orchestrator``). For each ``uncovered`` item,
   write a request bundle with sample-file paths + size + mtime so a sub-agent
   can read inside, classify the content type, and recommend an action.

The output is a coverage map at ``<system-dir>/coverage-audit.{md,json}``.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator


# --- channel rules ---------------------------------------------------------

# pack-personal.sh's hardcoded default target list.
PACK_PERSONAL_DEFAULTS: tuple[str, ...] = (
    "Documents", "Pictures", "Music", "Videos", "Desktop",
)

# pack-browsers.sh's snapshot scope.
PACK_BROWSERS_SCOPE: tuple[str, ...] = (
    ".mozilla", ".config/Cursor", ".cursor",
    ".config/chromium", ".config/google-chrome", ".config/opera",
    ".config/vivaldi", ".config/brave-browser",
)

# bundle.sh secrets target.
PACK_SECRETS_SCOPE: tuple[str, ...] = (".config/secrets",)

# bundle.sh's system.tar.gz captures ~/system (homing's own output).
BUNDLE_SYSTEM_SCOPE: tuple[str, ...] = ("system",)

# bundle.sh INCLUDE_CREDS=1 scope.
PACK_CREDS_SCOPE: tuple[str, ...] = (
    ".ssh", ".gnupg", ".aws", ".config/gh", ".docker/config.json",
    ".pki", ".config/Signal", "signal-desktop-keyring.gpg",
)

# bundle.sh INCLUDE_WALLETS=1 scope.
PACK_WALLETS_SCOPE: tuple[str, ...] = (
    "Monero", ".bitmonero", ".shared-ringdb",
    ".kaspa", ".kaspad", ".kdx", ".electrum", ".bitcoin", ".ethereum",
)

# Regenerable patterns — known to be safe to skip. These supersede the
# uncovered classification: anything matching here is considered
# intentionally-not-migrated.
REGENERABLE_PATTERNS: tuple[str, ...] = (
    # Caches
    ".cache", ".local/share/Trash", ".local/share/Steam/steamapps/shadercache",
    # Language/package caches (entire dirs — only the lock manifests in user
    # projects under Documents/ matter, those are inside pack-personal scope)
    ".npm", ".yarn", ".pnpm", ".pnpm-store", ".bun", ".nvm",
    ".cargo", ".rustup",
    ".gradle",  # Whole gradle dir is build cache + daemons
    ".dartServer", ".pub-cache",
    # Docker — config.json (auth) is captured by INCLUDE_CREDS; the rest is
    # regenerable images/buildx/desktop state.
    ".docker",
    # Android SDK + AVDs are huge and regenerable. AVD config can be lost.
    ".android", "Android",
    # Python distributions
    "anaconda3", "miniconda3", "miniforge3",
    # Go workspace
    "go/pkg", "go/bin",
    # IDE caches
    ".vscode-server", ".vscode-oss",
    # Generic install dirs
    ".npm-global", ".bin",
    # OS package managers / app stores — system-managed, regenerable
    "snap", ".var", ".local/share/flatpak",
    # XDG user-install dirs — caches, binaries, libraries that the user can
    # rebuild from package managers
    ".local/aws-cli", ".local/bin", ".local/lib", ".local/state",
    ".local/include", ".local/share/man", ".local/share/info",
    # Desktop environment state (regenerated by GNOME on first login)
    ".local/share/nautilus", ".local/share/xorg",
    ".local/share/grilo-plugins", ".local/share/desktop-directories",
    ".local/share/mime", ".local/share/sounds",
    ".local/share/evolution",  # GNOME mail/calendar (re-syncs from provider)
    ".local/share/tracker", ".local/share/tracker3",
    ".local/share/dbus-1",
    ".local/share/JetBrains",  # IDE state (re-syncs from cloud or .config)
    # Java state, language tooling
    ".java",
    # Build/run state
    ".dart-tool",
    # Editor swap files
    ".swp",
    # Misc OS state — regenerable from system packages on the destination
    ".icons", ".themes", ".fonts",
    ".local/share/icons", ".local/share/themes", ".local/share/fonts",
    ".local/share/backgrounds",
    ".local/share/recently-used.xbel",
    ".local/share/applications",
    ".local/share/gvfs-metadata",
    ".local/share/gnome-shell",
    ".local/share/gnome-settings-daemon",
    ".local/share/keyrings",  # GNOME keyring — wraps secrets but the master
                              # key is per-machine; restoring it on a different
                              # box won't decrypt without the user's login
                              # password being identical. Treated as
                              # regenerable; user re-enters secrets fresh.
    ".local/share/Steam",
    ".openjfx",
    # Migration self-output: don't audit our own bundle dir
    "migration-bundle-*",
    # X / wayland / DE state
    ".dbus", ".pulse", ".pulse-cookie",
)

# Container dirs we look INSIDE (one level deep) because they hold many
# unrelated child items. The parent itself is suppressed from the top-level
# walk — flagging "~/.local 22 GB uncovered" is misleading when all the real
# units live one level deeper. Children are individually classified.
HIDDEN_DIRS_TO_INSPECT: tuple[str, ...] = (
    ".config", ".local", ".local/share",
)


@dataclass(frozen=True, slots=True)
class CoverageItem:
    """One item discovered during the audit."""

    path: str  # relative to $HOME
    abs_path: str  # absolute path
    size_bytes: int
    last_mtime: float
    is_dir: bool
    is_symlink: bool
    bucket: str  # see channel rules above + "uncovered"
    rationale: str  # why it landed in this bucket
    # Filled in by the agentic phase (None if static-only audit)
    grade: str | None = None  # canonical | replaceable | regenerable | abandoned | decide
    content_class: str | None = None  # e.g. crypto-wallet, generated-content, app-data
    recommended_action: str | None = None  # bundle | pack-personal | skip | ask-user
    sample_files: tuple[str, ...] = field(default_factory=tuple)
    agent_notes: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# --- walk + static classify -----------------------------------------------


def _human_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{n:.1f}{unit}" if unit != "B" else f"{n}B"
        n = n / 1024  # type: ignore[assignment]
    return f"{n}TB"


def _matches(rel_path: str, scope: tuple[str, ...]) -> bool:
    """Is ``rel_path`` inside any of the given scope prefixes?

    Scope entries ending in ``*`` are treated as prefix wildcards
    (e.g. ``migration-bundle-*`` matches ``migration-bundle-pop-2026-04-28``).
    """
    rel = rel_path.rstrip("/")
    for s in scope:
        s = s.rstrip("/")
        if s.endswith("*"):
            if rel.startswith(s[:-1]):
                return True
        elif rel == s or rel.startswith(s + "/"):
            return True
    return False


def _chezmoi_managed_set(home: Path) -> set[str]:
    """Return the set of paths chezmoi tracks, relative to $HOME.

    Empty set if chezmoi isn't installed or has no source dir. Falls back
    silently — chezmoi is optional; many homing users won't have it.
    """
    src = home / ".local" / "share" / "chezmoi"
    if not src.is_dir():
        return set()
    try:
        import subprocess

        result = subprocess.run(
            ["chezmoi", "managed", f"--source={src}"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0:
            return set()
        return {line.strip() for line in result.stdout.splitlines() if line.strip()}
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return set()


def _classify_static(
    rel_path: str,
    chezmoi_set: set[str],
) -> tuple[str, str]:
    """Return (bucket, rationale) for ``rel_path`` using static rules."""
    if rel_path in chezmoi_set or any(rel_path.startswith(p + "/") for p in chezmoi_set):
        return ("chezmoi-managed", "tracked by chezmoi")
    if _matches(rel_path, PACK_PERSONAL_DEFAULTS):
        return ("pack-personal-default", "in pack-personal.sh defaults")
    if _matches(rel_path, PACK_BROWSERS_SCOPE):
        return ("pack-browsers-default", "in pack-browsers.sh scope")
    if _matches(rel_path, PACK_SECRETS_SCOPE):
        return ("pack-secrets-default", "in bundle.sh secrets")
    if _matches(rel_path, BUNDLE_SYSTEM_SCOPE):
        return ("bundle-system-default", "captured in bundle.sh system.tar.gz")
    if _matches(rel_path, PACK_CREDS_SCOPE):
        return ("pack-creds-conditional", "covered by INCLUDE_CREDS=1")
    if _matches(rel_path, PACK_WALLETS_SCOPE):
        return ("pack-wallets-conditional", "covered by INCLUDE_WALLETS=1")
    if _matches(rel_path, REGENERABLE_PATTERNS):
        return ("regenerable", "matches known regenerable pattern")
    return ("uncovered", "falls through every channel — needs decision")


def _safe_size(p: Path) -> int:
    """Best-effort recursive size; never raises on permission errors."""
    if p.is_file() or p.is_symlink():
        try:
            return p.lstat().st_size
        except OSError:
            return 0
    total = 0
    for root, dirs, files in os.walk(p, followlinks=False, onerror=lambda _: None):
        for name in files:
            try:
                total += os.lstat(os.path.join(root, name)).st_size
            except OSError:
                continue
    return total


def _safe_mtime(p: Path) -> float:
    try:
        return p.lstat().st_mtime
    except OSError:
        return 0.0


def _walk_targets(home: Path) -> Iterator[Path]:
    """Yield items the audit considers — top-level + selected container dirs.

    Container dirs (HIDDEN_DIRS_TO_INSPECT) are NOT yielded themselves — they
    hold many unrelated children, so flagging the parent as "uncovered" would
    be noise. Their children are walked individually.
    """
    seen: set[Path] = set()
    # Skip-set: container dirs whose CHILDREN are walked, not the parent.
    skip_parents = {home / d for d in HIDDEN_DIRS_TO_INSPECT}
    # Top-level
    try:
        for entry in sorted(home.iterdir()):
            if entry in skip_parents:
                continue
            if entry not in seen:
                seen.add(entry)
                yield entry
    except OSError:
        return
    # Look inside curated container dirs (one level deep) — catches items
    # like ~/.config/Signal that aren't visible from a top-level walk.
    for hidden_root in HIDDEN_DIRS_TO_INSPECT:
        d = home / hidden_root
        if not d.is_dir():
            continue
        try:
            for entry in sorted(d.iterdir()):
                if entry in skip_parents:
                    continue  # don't yield .local/share when we'll walk it next
                if entry not in seen:
                    seen.add(entry)
                    yield entry
        except OSError:
            continue


def audit_static(home: Path) -> list[CoverageItem]:
    """Run the static survey. No LLM, no network, deterministic."""
    home = home.expanduser().resolve()
    chezmoi_set = _chezmoi_managed_set(home)
    items: list[CoverageItem] = []
    for entry in _walk_targets(home):
        try:
            rel = str(entry.relative_to(home))
        except ValueError:
            continue
        bucket, rationale = _classify_static(rel, chezmoi_set)
        try:
            stat = entry.lstat()
            is_link = stat_is_link(stat)
            is_dir = (not is_link) and stat_is_dir(stat)
        except OSError:
            continue
        items.append(
            CoverageItem(
                path=rel,
                abs_path=str(entry),
                size_bytes=_safe_size(entry),
                last_mtime=_safe_mtime(entry),
                is_dir=is_dir,
                is_symlink=is_link,
                bucket=bucket,
                rationale=rationale,
            )
        )
    return items


def stat_is_link(stat) -> bool:  # noqa: D401 - tiny helper
    """``stat.S_ISLNK`` wrapper that doesn't import ``stat`` at module top."""
    import stat as _stat
    return _stat.S_ISLNK(stat.st_mode)


def stat_is_dir(stat) -> bool:
    import stat as _stat
    return _stat.S_ISDIR(stat.st_mode)


# --- agentic deep-dive (--via-orchestrator) ------------------------------


def sample_files_for(item: CoverageItem, max_samples: int = 6) -> list[str]:
    """Pick a small set of representative files inside an uncovered dir.

    Heuristic: prefer common manifests, README, the largest file, a few
    random entries. The sub-agent reads these to classify the content.
    """
    p = Path(item.abs_path)
    if not p.is_dir():
        return [item.abs_path]
    candidates: list[Path] = []
    preferred_names = (
        "README.md", "README", "package.json", "Cargo.toml", "pyproject.toml",
        "setup.py", "Makefile", "go.mod", "Gemfile", "composer.json",
        "wallet.dat", "*.keys", "*.kpk", "config.json", "manifest.json",
        ".gitignore", "schema.sql",
    )
    for pat in preferred_names:
        try:
            for match in sorted(p.glob(pat)):
                if match.is_file() and match not in candidates:
                    candidates.append(match)
                    if len(candidates) >= max_samples:
                        return [str(c) for c in candidates]
        except OSError:
            continue
    # Fall back to first N entries by name
    try:
        for entry in sorted(p.iterdir())[: max_samples - len(candidates)]:
            if entry.is_file() and entry not in candidates:
                candidates.append(entry)
    except OSError:
        pass
    return [str(c) for c in candidates]


def build_audit_request(item: CoverageItem) -> dict[str, Any]:
    """One JSON bundle per uncovered item for the orchestrator's sub-agent."""
    return {
        "path": item.abs_path,
        "rel_path": item.path,
        "size_bytes": item.size_bytes,
        "size_human": _human_size(item.size_bytes),
        "last_mtime_iso": datetime.fromtimestamp(
            item.last_mtime, tz=timezone.utc
        ).isoformat() if item.last_mtime > 0 else None,
        "is_dir": item.is_dir,
        "sample_files": sample_files_for(item),
        "user_message": (
            f"You are inspecting an uncovered $HOME item discovered by homing's "
            f"audit-coverage walk. The user is preparing to migrate this machine; "
            f"this item is not in any default migration channel and needs an "
            f"agentic decision.\n\n"
            f"Item: {item.path}\n"
            f"Absolute path: {item.abs_path}\n"
            f"Size: {_human_size(item.size_bytes)}\n"
            f"Last modified: "
            f"{datetime.fromtimestamp(item.last_mtime, tz=timezone.utc).isoformat() if item.last_mtime > 0 else 'unknown'}\n"
            f"Type: {'directory' if item.is_dir else 'file'}\n\n"
            f"Read a few of the sample files (paths above) to understand what "
            f"this is. Then emit a JSON object with:\n\n"
            f"  - content_class: one of\n"
            f"      crypto-wallet, app-data, generated-content, project-source,\n"
            f"      vendored-tooling, archive, dataset, document-pile,\n"
            f"      configuration, build-artifact, abandoned-project, unknown\n"
            f"  - grade: one of\n"
            f"      canonical    (irreplaceable, must migrate — wallet keys, original docs, code with no remote)\n"
            f"      replaceable  (exists upstream — vendored deps, model checkpoints, downloaded installers)\n"
            f"      regenerable  (produced by tools — caches, build artifacts)\n"
            f"      abandoned    (touched > 1 year ago, no recent activity, low signal)\n"
            f"      decide       (mixed / unclear — surface to the user)\n"
            f"  - recommended_action: one of\n"
            f"      bundle              (encrypt + ship in bundle, e.g. wallet keys)\n"
            f"      pack-personal       (rsync to personal/ section of drive)\n"
            f"      skip-regenerable    (don't migrate, will recreate on destination)\n"
            f"      ask-user            (require explicit user decision)\n"
            f"  - notes: one short sentence justifying the grade + action.\n\n"
            f"Be specific. The user values 'zero tolerance for wrong facts' — if "
            f"unsure, return grade=decide and recommended_action=ask-user."
        ),
        "schema": {
            "content_class": "string",
            "grade": "canonical | replaceable | regenerable | abandoned | decide",
            "recommended_action": "bundle | pack-personal | skip-regenerable | ask-user",
            "notes": "string",
        },
    }


# --- output --------------------------------------------------------------


def render_markdown(items: list[CoverageItem]) -> str:
    """Render a human-readable coverage report grouped by bucket."""
    by_bucket: dict[str, list[CoverageItem]] = {}
    for item in items:
        by_bucket.setdefault(item.bucket, []).append(item)

    bucket_order = (
        "uncovered",
        "pack-creds-conditional",
        "pack-wallets-conditional",
        "chezmoi-managed",
        "pack-personal-default",
        "pack-browsers-default",
        "pack-secrets-default",
        "regenerable",
    )
    bucket_titles = {
        "uncovered": "⚠ UNCOVERED — fall through every default channel",
        "pack-creds-conditional": "Conditional creds (set INCLUDE_CREDS=1 to capture)",
        "pack-wallets-conditional": "Conditional wallets (set INCLUDE_WALLETS=1 to capture)",
        "chezmoi-managed": "✓ chezmoi-managed (in dotfiles bundle)",
        "pack-personal-default": "✓ pack-personal default targets",
        "pack-browsers-default": "✓ pack-browsers scope",
        "pack-secrets-default": "✓ secrets bundle",
        "regenerable": "regenerable (intentionally skipped)",
    }

    lines = [
        "# Coverage audit",
        "",
        f"_Generated: {datetime.now(timezone.utc).isoformat()}_",
        "",
        f"- {len(items)} items audited",
        f"- {len(by_bucket.get('uncovered', []))} uncovered",
        "",
    ]
    total_uncovered = sum(i.size_bytes for i in by_bucket.get("uncovered", []))
    if total_uncovered > 0:
        lines.append(
            f"Uncovered total size: **{_human_size(total_uncovered)}** — "
            f"these are the items that would not migrate without explicit action.\n"
        )
    for bucket in bucket_order:
        bucket_items = by_bucket.get(bucket, [])
        if not bucket_items:
            continue
        lines.append(f"## {bucket_titles[bucket]} ({len(bucket_items)})")
        lines.append("")
        for item in sorted(bucket_items, key=lambda i: -i.size_bytes):
            size_str = _human_size(item.size_bytes)
            kind = "dir" if item.is_dir else ("link" if item.is_symlink else "file")
            grade = f" — **{item.grade}**" if item.grade else ""
            action = f" → {item.recommended_action}" if item.recommended_action else ""
            notes = f" _({item.agent_notes})_" if item.agent_notes else ""
            lines.append(
                f"- `~/{item.path}` ({kind}, {size_str}){grade}{action}{notes}"
            )
            lines.append(f"  - {item.rationale}")
        lines.append("")
    # Catch-all for any unknown buckets
    for bucket, bucket_items in by_bucket.items():
        if bucket in bucket_order or not bucket_items:
            continue
        lines.append(f"## {bucket} ({len(bucket_items)})")
        lines.append("")
        for item in bucket_items:
            lines.append(f"- `~/{item.path}` — {item.bucket}: {item.rationale}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_outputs(
    items: list[CoverageItem],
    system_dir: Path,
) -> tuple[Path, Path]:
    system_dir = system_dir.expanduser().resolve()
    system_dir.mkdir(parents=True, exist_ok=True)
    md_path = system_dir / "coverage-audit.md"
    json_path = system_dir / "coverage-audit.json"
    md_path.write_text(render_markdown(items), encoding="utf-8")
    json_path.write_text(
        json.dumps([i.to_dict() for i in items], indent=2, default=str),
        encoding="utf-8",
    )
    return md_path, json_path
